### ISSUE TITLE
SpeechKit Logo

### ISSUE THREAD

**Issue by batarian71** [wcoder/Yandex.SpeechKit.Xamarin#2]
Hi again! @wcoder 

I designed a logo. I hope you like it. What do you think?

![speechkit](https://user-images.githubusercontent.com/36008612/40282490-d74818ea-5c78-11e8-8f6f-6f82ef97f765.jpg)

**Comment by wcoder** [comment]
Hi @batarian71 thank you for logos again!

I think the first logo is better.
